# Step 1: Use a base image that has JDK installed
FROM openjdk:17-jdk-slim

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy the JAR file generated by your build tool (Maven or Gradle)
# Make sure the path matches where your JAR is being built
COPY target/cashier-spring-0.0.1-SNAPSHOT.jar app.jar

# Step 4: Expose the application port (optional, matches Spring Boot default port)
EXPOSE 5000

# Step 5: Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]
