version: '3.8'

services:
  spring-app:
    image: cashier-spring-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      - postgres_db
    networks:
      - cashier-network

  postgres_db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: cashier_spring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - cashier-network

networks:
  cashier-network:
    driver: bridge

volumes:
  pg-data:
    driver: local
